[package]
name = "rust_server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
axum-server = "0.7.2"
tokio = { version = "1.47.1", features = ["full"] }

[dev-dependencies]
reqwest = "0.12.23"
