FROM rust:latest AS builder
WORKDIR /app

# Cache dependencies
COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build --release

# Copy actual source and build
COPY . .
RUN cargo build --release

FROM rust:latest AS builder
WORKDIR /app
COPY . .
# RUN cargo build --release
RUN --mount=type=cache,target=/app/target/ \
    --mount=type=cache,target=/usr/local/cargo/git/db \
    --mount=type=cache,target=/usr/local/cargo/registry/ \
    cargo build --release

FROM debian:bullseye-slim
COPY --from=builder /app/target/release/rust_server /usr/local/bin/rust_server
ENTRYPOINT ["rust_server"]
